Some systems define ERR as something.  illumos does in: /usr/include/sys/regset.h when __EXTENSIONS__ is defined, which we want for other things.  Yeah, it would be better if this header were not polluting the namespace so much.
../source4/heimdal/lib/hcrypto/libtommath/bn_mp_karatsuba_mul.c: In function ‘mp_karatsuba_mul’:
../source4/heimdal/lib/hcrypto/libtommath/bn_mp_karatsuba_mul.c:63: error: expected identifier or ‘*’ before numeric constant
../source4/heimdal/lib/hcrypto/libtommath/bn_mp_karatsuba_mul.c:160: warning: statement with no effect
../source4/heimdal/lib/hcrypto/libtommath/bn_mp_karatsuba_mul.c:160: error: expected ‘;’ before ‘:’ token